### ISSUE TITLE
Ansonsten leerer [Unreleased]-Abschnitt liefert false positive

### ISSUE THREAD

**Issue by jonasholtkamp** [PeterWippermann/changelog-buildbreaker#1]
Wie vorhin schon angedeutet führt es zum Fehler wenn es zwar einen `[Unreleased]`-Abschnitt gibt, dieser aber ansonsten leer ist - wie es häufig beim Release gemacht wird. Nach dem `[Unreleased]` können beliebig viele Leerzeilen folgen.

```
# Change Log
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/) 
and this project adheres to [Semantic Versioning](http://semver.org/).

## [Unreleased]
## [Some quite old version]
### Added
- A fancy new feature nobody really needs #YAGNI

...
```

Das von dir angesprochene komplizierte Matching ist IMO nicht nötig, wenn du weiterhin (so sah es zumindest im Log aus) auf RegEx setzt - da hilft dann vielleicht [Lookahead Assertion](https://www.regular-expressions.info/lookaround.html): `\[Unreleased\](?!\s*##\s)` - ungetestet!

**Comment by PeterWippermann** [comment]
Hallo @jonasholtkamp,
danke für den Hinweis! Ich bin davon ausgegangen, dass man die `Unreleased` section bei jedem Release entfernt und bei neuen Änderungen wieder hinzufügt. Das hätte ich natürlich [leicht nachlesen können](http://keepachangelog.com/en/1.0.0/)...

Ist jetzt aber gefixt! Der RegEx ist zwar um einiges komplizierter (`\R(?<section>##\h*\[Unreleased\]\h*)\R(?:\h*\R)*(?<content>\h*(?!##\h*\[)\p{Graph}+.*)\R`), kommt dafür aber auch mit zusätzlichen Whitespaces zurecht.

**Comment by jonasholtkamp** [comment]
Nice one, thanks for attending to this. 🕵️
