### ISSUE TITLE
Desired behaviour? [Unreleased] in first line doesn't lead to failure

### ISSUE THREAD

**Issue by jonasholtkamp** [PeterWippermann/changelog-buildbreaker#2]
Hi, it's me again,

I noticed the following behaviour - is that desired?

This fails as expected - notice the two blank lines:
```

## [Unreleased]
### Added

```

However without either of the surrounding new lines (regardless of `\n`, `\r`, `\r\n`) the build does *not* fail.

I wrote a [test](https://github.com/jonasholtkamp/changelog-buildbreaker/blob/feature/create-tests/src/test/java/com/github/peterwippermann/maven/changelogbuildbreaker/ChangelogCheckerMojoTest.java#L83-L84) that demonstrates this (IMO wrong) behaviour ([the corresponding CHANGELOG.md](https://github.com/jonasholtkamp/changelog-buildbreaker/blob/0d7ad25ac14afe52e9848e3b01e9cbf2c96cdfb1/src/test/resources/CHANGELOG-non-empty-unreleased-missing-starting-new-line.MD)).

**Comment by PeterWippermann** [comment]
Thanks for your PR! :-)
