### ISSUE TITLE
Introduce a prefix

### ISSUE THREAD

**Issue by PeterWippermann** [PeterWippermann/changelog-buildbreaker#4]
So the call `com.github.peterwippermann.maven:changelog-buildbreaker-maven-plugin:check` can be replaced with `changelog-buildbreaker:check`.

**Comment by jonasholtkamp** [comment]
From https://maven.apache.org/guides/plugin/guide-java-plugin-development.html:

> You can assign a shortened prefix to your plugin, such as `mvn hello:sayhi`. This is done automatically if you follow the convention of using `${prefix}-maven-plugin` (or `maven-${prefix}-plugin` if the plugin is part of the Apache Maven project).

Addendum: I tested it. Just providing `changelog-buildbreaker:check` works out-of-the-box.

**Comment by PeterWippermann** [comment]
You're right. I even had configured it explicitly before. I just should have tested it...
