### ISSUE TITLE
Default filename with lowercase file suffix

### ISSUE THREAD

**Issue by PeterWippermann** [PeterWippermann/changelog-buildbreaker#5]
Replace `CHANGELOG.MD`with `CHANGELOG.md`.

**Comment by jonasholtkamp** [comment]
Why not even detecting automatically whether a uppercase or lowercase suffix is used?

**Comment by PeterWippermann** [comment]
I'd loved to have Maven done this automatically for me! But similar to `project.build.sourceEncoding` Maven plugins have to implement this kind of generally applicable logic all by themselves...

Having that said, I think it's important to respect that capitalisation matters on Unix systems. All kind of detection logic may cause more problems than it solves. So I decided to stick to the standard, which says:

> "What should the changelog file be named? Call it CHANGELOG.md"
